# Generated by Django 4.1.1 on 2022-09-20 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(default='CN000', max_length=5, unique=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('semmester', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('seat_count', models.IntegerField(blank=True, default=0, null=True)),
                ('max_seat', models.IntegerField(blank=True, null=True)),
                ('quota', models.BooleanField(default=True)),
                ('attend', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
